In [1]:
import pandas as pd
import numpy as np
import gc
from IPython.display import display
from mnp.ingestion.loader import load_endes
from mnp.utils.profiler import centrar_notebook
from mnp.utils.cleaning import run_phase1_engine
# Configuración visual
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
centrar_notebook()

print("[OK]")

2026-06-14 12:34:51.155 | INFO     | mnp.config:<module>:11 - PROJ_ROOT path is: /Users/abelguevarah/Desktop/invs/malnutrition-research

[OK]

In [2]:
# Carga de datos
history = load_endes(
        year=range(2007, 2025),
        module="household",
        record="household_characteristics",
        meta=True
    )

dfs = []
col_labels_hist = {}
val_labels_hist = {}

for year in sorted(list(history.keys())):
    year_df, year_meta = history.pop(year)
    col_labels_hist[year] = year_meta.column_names_to_labels
    val_labels_hist[year] = year_meta.variable_value_labels
    
    dfs.append(year_df.assign(year=year))

df_raw = pd.concat(dfs, ignore_index=True)
del dfs
gc.collect()

print(f"[OK] Data RECH6 cargada: {len(df_raw)} filas y {df_raw.shape[1]} columnas.")
print(f"[OK] Diccionario cargado: {len(col_labels_hist)} Column Labels, {len(val_labels_hist)} Value Labels")

2026-06-14 12:34:55.400 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:55.767 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.sav desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:56.186 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:56.523 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:56.857 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.sav desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:57.169 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.sav desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:57.506 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:57.882 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:58.375 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:58.833 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:59.358 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:34:59.924 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:35:00.402 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo64 [Alias: household_characteristics]
2026-06-14 12:35:00.921 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.sav desde Modulo1629 [Alias: household_characteristics]
2026-06-14 12:35:01.458 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.SAV desde Modulo1629 [Alias: household_characteristics]
2026-06-14 12:35:01.983 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0.sav desde Modulo1629 [Alias: household_characteristics]
2026-06-14 12:35:02.518 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0_2023.sav desde Modulo1629 [Alias: household_characteristics]
2026-06-14 12:35:03.068 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH0_2024.sav desde Modulo1629 [Alias: household_characteristics]
2026-06-14 12:35:03.603 | SUCCESS  | mnp.ingestion.loader:_load_multiple_years:290 - ✅ ¡Historia cargada y organizada por años!
[OK] Data RECH6 cargada: 608995 filas y 62 columnas.
[OK] Diccionario cargado: 18 Column Labels, 18 Value Labels

In [3]:
# Inspeccionar variable
# df_raw['HC51'].value_counts(dropna=False)
df_raw.head(10)

,HHID,HV000,HV001,HV002,HV003,HV004,HV005,HV006,HV007,HV008,HV009,HV010,HV011,HV012,HV013,HV014,HV015,HV016,HV017,HV018,HV019,HV020,HV021,HV022,HV023,HV024,HV025,HV026,HV027,HV028,HV030,HV031,HV032,HV033,HV035,HV040,HV041,HV042,HV043,HV044,year,HV005A,ID1,longitudx,latitudy,HV002A,hv005,HV005X,hv022,codccpp,nomccpp,long_ccpp,lat_ccpp,ubigeo,nconglome,CODCCPP,NOMCCPP,UBIGEO,NCONGLOME,LONGITUDX,LATITUDY,NCONGLOME1
0,1 4,PE5,1.0,4.0,1.0,1.0,313643.0,3.0,2005.0,1263.0,3.0,1.0,0.0,3.0,3.0,0.0,1.0,30.0,2.0,7.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,1.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 10,PE5,1.0,10.0,4.0,1.0,313643.0,3.0,2005.0,1263.0,4.0,1.0,0.0,4.0,2.0,1.0,1.0,29.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,1.0,2335.0,1.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 16,PE5,1.0,16.0,2.0,1.0,313643.0,3.0,2005.0,1263.0,5.0,2.0,0.0,5.0,5.0,0.0,1.0,31.0,3.0,7.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,2.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 22,PE5,1.0,22.0,2.0,1.0,313643.0,3.0,2005.0,1263.0,5.0,2.0,0.0,5.0,5.0,1.0,1.0,29.0,1.0,31.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,1.0,2335.0,2.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 28,PE5,1.0,28.0,0.0,1.0,0.0,3.0,2005.0,1263.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,30.0,1.0,7.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,0.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 34,PE5,1.0,34.0,2.0,1.0,313643.0,3.0,2005.0,1263.0,3.0,1.0,0.0,3.0,2.0,1.0,1.0,31.0,3.0,31.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,1.0,2335.0,1.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 40,PE5,1.0,40.0,1.0,1.0,313643.0,3.0,2005.0,1263.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,31.0,1.0,7.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,0.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1 46,PE5,1.0,46.0,2.0,1.0,313643.0,3.0,2005.0,1263.0,3.0,1.0,0.0,3.0,2.0,0.0,1.0,30.0,1.0,31.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,1.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 52,PE5,1.0,52.0,2.0,1.0,313643.0,3.0,2005.0,1263.0,4.0,1.0,0.0,4.0,4.0,1.0,1.0,30.0,1.0,7.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,1.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1 58,PE5,1.0,58.0,1.0,1.0,313643.0,3.0,2005.0,1263.0,10.0,4.0,0.0,10.0,10.0,1.0,1.0,30.0,1.0,31.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,2.0,0.0,NaN,1.0,NaN,8.0,108696.0,0.0,2335.0,4.0,1.0,0.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
from mnp.utils.cleaning import run_phase1_engine
from mnp.configs.rech0 import config_f1

# 3. Limpiar
df_clean = run_phase1_engine(df_raw, config_f1)

print(f'[OK] Limpieza biológica completa. Shape: {df_clean.shape}')
df_clean.head(5)

[Limpieza] Iniciando Motor Fase 1...
[Limpieza] Eliminando 23 columnas (Optimización RAM)...
[Limpieza] Drops iniciales completados en 0.00s
[Limpieza] Casteando 14 columnas clave...
[Limpieza] Casteo completado en 5.18s
[Limpieza] Escalamiento matemático (x/1,000,000)...
[Limpieza] Escalamiento /1M completado en 0.00s
[Limpieza] Ejecutando Coalesce (Unificación de columnas)...
[Limpieza] Coalesce completado en 0.16s
[Limpieza] Filtrando filas por valores válidos...
[Limpieza] Filtro completado en 0.18s. Filas removidas: 39712
[Limpieza] Motor Fase 1 finalizado. Tiempo total: 5.53s
[OK] Limpieza biológica completa. Shape: (569283, 28)

,HHID,HV001,HV002,HV004,HV005,HV008,HV009,HV010,HV012,HV013,HV014,HV015,HV021,HV022,HV024,HV025,HV026,HV035,HV040,year,ID1,HV002A,CODCCPP,NOMCCPP,UBIGEO,NCONGLOME,LONGITUDX,LATITUDY
0,1 4,1,4,1.0,0.313643,1263.0,3.0,1.0,3.0,3.0,0.0,1.0,1,0.0,1.0,1.0,2.0,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 10,1,10,1.0,0.313643,1263.0,4.0,1.0,4.0,2.0,1.0,1.0,1,0.0,1.0,1.0,2.0,1.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 16,1,16,1.0,0.313643,1263.0,5.0,2.0,5.0,5.0,0.0,1.0,1,0.0,1.0,1.0,2.0,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 22,1,22,1.0,0.313643,1263.0,5.0,2.0,5.0,5.0,1.0,1.0,1,0.0,1.0,1.0,2.0,1.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 34,1,34,1.0,0.313643,1263.0,3.0,1.0,3.0,2.0,1.0,1.0,1,0.0,1.0,1.0,2.0,1.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
from importlib import reload
import mnp.utils.cleaning
reload(mnp.utils.cleaning)
from mnp.utils.cleaning import apply_standard_labels
from mnp.configs.rech0 import config_f1, config_f3
# Le pasamos config_f1 para que el motor sepa mágicamente dónde buscar 
# gracias a tus propias reglas de Coalesce.
df_final = apply_standard_labels(df_clean, val_labels_hist, config_f3, config_f1)
print(f"[OK] Fase 3 (Estandarización de Etiquetas) completada.")
df_final.head(15)

[OK] Fase 3 (Estandarización de Etiquetas) completada.

,HHID,HV001,HV002,HV004,HV005,HV008,HV009,HV010,HV012,HV013,HV014,HV015,HV021,HV022,HV024,HV025,HV026,HV035,HV040,year,ID1,HV002A,CODCCPP,NOMCCPP,UBIGEO,NCONGLOME,LONGITUDX,LATITUDY
0,1 4,1,4,1.0,0.313643,1263.0,3.0,1.0,3.0,3.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 10,1,10,1.0,0.313643,1263.0,4.0,1.0,4.0,2.0,1.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,1.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 16,1,16,1.0,0.313643,1263.0,5.0,2.0,5.0,5.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 22,1,22,1.0,0.313643,1263.0,5.0,2.0,5.0,5.0,1.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,1.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 34,1,34,1.0,0.313643,1263.0,3.0,1.0,3.0,2.0,1.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,1.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 40,1,40,1.0,0.313643,1263.0,1.0,0.0,1.0,1.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1 46,1,46,1.0,0.313643,1263.0,3.0,1.0,3.0,2.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 52,1,52,1.0,0.313643,1263.0,4.0,1.0,4.0,4.0,1.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1 58,1,58,1.0,0.313643,1263.0,10.0,4.0,10.0,10.0,1.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1 64,1,64,1.0,0.313643,1263.0,3.0,1.0,3.0,3.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1 81,1,81,1.0,0.313643,1263.0,2.0,1.0,2.0,2.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1 87,1,87,1.0,0.313643,1263.0,1.0,1.0,1.0,1.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1 93,1,93,1.0,0.313643,1263.0,2.0,0.0,2.0,1.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1 99,1,99,1.0,0.313643,1263.0,5.0,1.0,5.0,5.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1105,1,105,1.0,0.313643,1263.0,5.0,1.0,5.0,5.0,0.0,Completo,1,0.0,Amazonas,Urbano,Pueblo,0.0,2335.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
from mnp.config import INTERIM_DATA_DIR
import os
# Aseguramos que la carpeta interim exista
os.makedirs(INTERIM_DATA_DIR, exist_ok=True)
# Ruta del archivo final
output_path = INTERIM_DATA_DIR / "rech0_cleaned.parquet"
# Guardamos en formato parquet (preserva tipos de datos y ahorra RAM)
df_final.to_parquet(output_path, index=False)
print(f"[OK] Datos RECH0 (Fase 1, 2 y 3) guardados exitosamente en:")
print(f"-> {output_path}")

[OK] Datos RECH0 (Fase 1, 2 y 3) guardados exitosamente en:
-> /Users/abelguevarah/Desktop/invs/malnutrition-research/data/interim/rech0_cleaned.parquet

In [ ]:
import sweetviz as sv
# reporte_sv = sv.analyze(df_final)
# reporte_sv.show_html('data/interim/rech6_sweetviz_report.html')
# reporte_sv.show_notebook(w="100%", h="800", filepath='data/interim/rech6_sweetviz_report.html')